version: "3.9"
services:
  pikuchat:
    build:
      context: .
      target: builder
    ports:
      - 4455:4455
    volumes:
      - .:/app
      - tmp:/app/tmp
      - gopath:/go
    environment:
      PORT: 4455
volumes:
  tmp:
  gopath:
